# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(schema)
add_subdirectory(mcap)
add_subdirectory(deviceio_trackers)
add_subdirectory(replay_deviceio_session)
add_subdirectory(live_trackers)
add_subdirectory(log_bridge)
add_subdirectory(plugin_manager)
